version: '3'

networks:
  goodnight:

services:
  postgres:
    image: postgres:11
    restart: always
    environment:
    - POSTGRES_DB=goodnight
    - POSTGRES_USER=goodnight
    - POSTGRES_PASSWORD=EtyUPqs92FPyCeFCzb/3YQ
    volumes:
    - ./db/postgres/data:/var/lib/postgresql/data
    networks:
    - goodnight

  goodnight:
    build: .
    ports:
    - 9000:9000
    environment:
    - APPLICATION_SECRET=Qa075HhhWoSerKWDFWFQA1Hwz6tb8K4cK1Y6anZS3HI
    - DATABASE_SERVER=postgres
    - DATABASE_PORT=5432
    - DATABASE_NAME=goodnight
    - DATABASE_USER=goodnight
    - DATABASE_PASSWORD=EtyUPqs92FPyCeFCzb/3YQ
    links:
    - postgres
    networks:
    - goodnight
