
kind: pipeline
type: docker
name: default

trigger:
  branch:
    - release

steps:
  - name: build
    image: plugins/docker
    settings:
      repo: goodnight
      dry_run: true
      auto_tag: true
