version: '3'

services:
  postgres:
    image: postgres:11
    restart: always
    environment:
    - POSTGRES_DB=goodnight
    - POSTGRES_USER=goodnight
    - POSTGRES_PASSWORD=EtyUPqs92FPyCeFCzb/3YQ
    volumes:
    - ./db/postgres/data:/var/lib/postgresql/data
    ports:
      - 6432:5432

  goodnight:
    build: .
    ports:
    - 9000:9000
    environment:
    - APPLICATION_SECRET=Qa075HhhWoSerKWDFWFQA1Hwz6tb8K4cK1Y6anZS3HI
    - DATABASE_URL=jdbc:postgresql://postgres:6432/goodnight?currentSchema=public
    - DATABASE_USER=goodnight
    - DATABASE_PASSWORD=EtyUPqs92FPyCeFCzb/3YQ
    links:
    - postgres
